### ISSUE TITLE
Private Api search without query

### ISSUE THREAD

**Issue by reteps** [BackInBash/DeezerSync#23]
hello, I am experimenting with the internal deezer api and I was wondering if the private api queries differently than the public one. Can you leave the query parameter blank for a search and see if anything is returned?

**Comment by BackInBash** [comment]
I´ve testet it.

Request URL:
https://www.deezer.com/ajax/gw-light.php?method=deezer.pageSearch&input=3&api_version=1.0&api_token={APIKEY}&cid=731769655

Request Body:
```json
{
    "query": "",
    "start": 0,
    "nb": 40,
    "suggest": true,
    "artist_suggest": true,
    "top_tracks": true
}
```

Response:
```json
{
    "error": {
        "REQUEST_ERROR": "Query is empty"
    },
    "results": {},
    "payload": null
}
```
