### ISSUE TITLE
How do you connect to Deezer ?

### ISSUE THREAD

**Issue by xfischer** [BackInBash/DeezerSync#3]
Hi @BackInBash.

I'd like to use your repo to organize my Deezer playlists.
How do you connect to Deezer ? I have an an set up in Deezer API, but I cannot se how to login.

Thanks !

**Comment by BackInBash** [comment]
Hi, i´m using the private Deezer API.
For now you have to enter your `arl` Cookie Token (https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr/wiki/How-to-login-via-cookie) in the `DeezerSync/DeezerSync/DeezerSync/Deezer/API/Login.cs`
```csharp
private string secret = "YOUR_TOKEN_GOES_HERE";
```

**Comment by BackInBash** [comment]
If you are able to get better search results. Please open up a Pull :wink:

**Comment by xfischer** [comment]
Cool ! Thanks. I'll let you know!
